[package]
name = "bitmap_rs"
version = "0.1.0"
authors = ["Florian Sextl <sextl@in.tum.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.2"
custom_debug_derive = "0.5.0"
thiserror = "1"
